### ISSUE TITLE
Forgot password alert having issues

### ISSUE THREAD

**Issue by Jayasimman** [Sundar-Infographic-Analytics/tax_mobile_end#5]
![Screenshot_20210429-195027](https://user-images.githubusercontent.com/68588689/116566234-364f1000-a924-11eb-9876-0d9d4f0ff05b.jpg)

**Comment by Jayasimman** [comment]
First password field check validation,
Second one is check validation and password match.

**Comment by nandhinirakshan123** [comment]
Fixed this issue
